1622 add sites table
ShelterTechSF/askdarcel-api pull request #538
Opened 2020-09-28 03:59 UTC by katerina-kossler

Add Sites table with site_code (string)
Add join table between Sites and Resources for many-to-many relationship

2020-10-10 03:43 UTC, jjfreund requested changes
The migration looks good. I think we also want a many-many relationship between sites and categories, as they will also be site-specific.

We also will want to add the rails domain object for sites (and modify resources & categories) but that can be done in a different commit.

2020-10-10 03:45 UTC, jjfreund requested changes

2020-10-10 03:45 UTC, jjfreund commented on db/migrate/20200928034548_create_sites.rb
> +      t.column :site_code, :integer, default: 'sfsg'
This should be a string no?

2020-10-10 05:33 UTC, katerina-kossler commented on db/migrate/20200928034548_create_sites.rb
> +      t.column :site_code, :integer, default: 'sfsg'
Yes!

2020-10-13 16:05 UTC, jjfreund approved these changes
lgtm! Not sure if we need the default value for site code but that shouldn't be harmful.

2020-10-13 18:02 UTC, merged